force-app/main/default/objects/Contact/fields/Annual_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Income</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Credit Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <description>Borrower detail for Loan application</description>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/Loan_Application__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represent the Primary Applicant for Loan Application</description>
    <label>Borrower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LoanApplicationValidator.cls
public with sharing class LoanApplicationValidator {
    
    public static void handleSubmission(List<Loan_Application__c> loanApps) {
        Set<Id> borrowerIds = new Set<Id>();
        Boolean isSubmitting = false;

        for (Loan_Application__c la :loanApps) {
            if (la.Borrower__c != null) {
                borrowerIds.add(la.Borrower__c);
            }       
        }
        // One query to collect all the Borrower(Contact) Ids for Validation and later use
        Map<Id, Contact> borrowerMap = BorrowerSelector.newInstance().getBorrowerMap(borrowerIds);

        for (Loan_Application__c la :loanApps) {
            // 1) Amount > 0
            if (la.Amount__c == null || la.Amount__c <= 0) {
                la.addError('Amount must be greater than 0 when submitting.');
            }
            // 2) Borrower must be present
            if (la.Borrower__c == null) {
                la.addError('Borrower is required to submit the application.');
                return;
            }
            Contact borrower = borrowerMap.get(la.Borrower__c);
            // 3) Borrower data: Email present, Income > 0, Credit Score present
            if (borrower.Credit_Score__c == null) {
                la.addError('Borrower Credit Score is required.');
            }
            if (String.isBlank(borrower.Email)) {
                la.addError('Borrower must have an Email.');
            }
            if (borrower.Annual_Income__c == null || borrower.Annual_Income__c <= 0) {
                la.addError('Borrower Annual Income must be greater than 0.');
            }  
        }
    }
}