force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Base_Rate__c.field-meta.xml
<CustomField>
    <fullName>Base_Rate__c</fullName>
    <label>Base Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Interest_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Type__c</fullName>
    <label>Interest Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Max_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Max Loan Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Min_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Min_Credit_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Min Credit Score</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Min_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Loan_Amount__c</fullName>
    <label>Min Loan Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Adjustable</fullName>
            </value>
            <value>
                <fullName>Interest-Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductSelector.cls
public inherited sharing class ProductSelector extends fflib_SObjectSelector implements IProductSelector{
    
    /* 1. sObjectField list */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Product__c.Id,
            Product__c.Name,
            Product__c.Min_Credit_Score__c,
            Product__c.Base_Rate__c,
            Product__c.Product_Type__c,
            Product__c.Max_Loan_Amount__c,
            Product__c.Min_Loan_Amount__c,
            Product__c.Interest_Rate_Type__c
        };
    }

     /* 2. Boilerplate code */
    public Schema.SObjectType getSObjectType(){
		return Product__c.SObjectType;
	}

    public static ProductSelector newInstance() {
        return new ProductSelector();
    }
  
    public fflib_QueryFactory getQueryFactory() {
        return new fflib_QueryFactory(getSObjectType());
    }

    /* 3. Selector Methods */
    public List<Product__c> selectByIds(Set<Id> idSet) {
        if (idSet.isEmpty()) {
            return new List<Product__c>();
        }
 
        fflib_QueryFactory qf = getQueryFactory();
        qf.selectFields(getSObjectFieldList());
        qf.setCondition('Id IN :idSet');
        return Database.query(qf.toSOQL());
    }

    public Product__c selectById(Id productId) {
        List<Product__c> rows = (List<Product__c>) this.selectByIds(new Set<Id>{ productId });
        return rows.isEmpty() ? null : rows[0];
    }

    // Best eligible product for a given credit score 
    public Product__c selectBestEligibleProduct(Decimal borrowerCreditScore) {
        String whereClause = 'Min_Credit_Score__c <= :borrowerCreditScore';
        fflib_QueryFactory qf = getQueryFactory();

        qf.selectFields(getSObjectFieldList())
        .setCondition(whereClause)
        .addOrdering(Product__c.Base_Rate__c,fflib_QueryFactory.SortOrder.ASCENDING, true)
        .addOrdering(Product__c.Min_Credit_Score__c,fflib_QueryFactory.SortOrder.DESCENDING)
        .setLimit(1);
        List<Product__c> rows = Database.query(qf.toSOQL());
        
        return rows.isEmpty() ? null : rows[0];
    }
}