force-app/main/default/objects/Contact/recordTypes/Borrower.recordType-meta.xml
<RecordType>
    <fullName>Borrower</fullName>
    <active>true</active>
    <description>Borrower detail for Loan application</description>
    <label>Borrower</label>
</RecordType>

force-app/main/default/objects/Loan_Application__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represent the Primary Applicant for Loan Application</description>
    <label>Borrower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Selected_Product__c.field-meta.xml
<CustomField>
    <fullName>Selected_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Represent the status of Loan</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Base_Rate__c.field-meta.xml
<CustomField>
    <fullName>Base_Rate__c</fullName>
    <label>Base Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Min_Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Min_Credit_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Min Credit Score</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TaskServiceTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TaskServiceTest {

     @testSetup
    static void setupData() {

        Map<String, SObject> personAccount = TestData.createPersonAccountBorrower();

        // Minimal Contact (Borrower)
        Contact borrower = (Contact) personAccount.get('Contact');

        // Minimal Product
        Product__c product = new Product__c(
            Name = 'Conv 30Y',
            Min_Credit_Score__c = 620,
            Base_Rate__c = 6.00
        );
        insert product;

        // Draaft to Approve Loan Application 
        insert new Loan_Application__c(
            Borrower__c = borrower.Id,
            Selected_Product__c = product.Id,
            Amount__c = 500000,
            Status__c = 'Draft'
        );
    }
  
    // Create a new task for the Loan Application
    @IsTest(SeeAllData=false)
    private static void testPreparesTaskForApprovedLoan() {
        List<Loan_Application__c> approvedLApps = new List<Loan_Application__c>();
        
        Loan_Application__c la = [
            SELECT Id, Status__c, OwnerId
            FROM Loan_Application__c
            LIMIT 1
        ];
        approvedLApps.add(la);

        Test.startTest();
        TaskService.prepareDocsTasks(approvedLApps, 'testSubject', 'Loan Application');
        Test.stopTest();

        // Assert a Task was created for this loan
        List<Task> tasks = [
            SELECT Id, WhatId, Subject, Status, Priority, ActivityDate
            FROM Task
            WHERE WhatId = :la.Id
        ];
        System.assertEquals(1, tasks.size(), 'Exactly one Task should be created for Approved loan.');
        System.assertEquals(la.Id, tasks[0].WhatId, 'Task.WhatId should reference the Loan Application.');
        System.assertEquals(true, String.isNotBlank(tasks[0].Subject), 'Task subject should be set.');
    }

    
    // Negative senario when passing null loan application Id
    @IsTest
    private static void negativeNullLoanId() {
        String error;

        Test.startTest();
        try {
            TaskService.prepareDocsTasks(null, 'testSubject', 'Loan Application');
        }catch (Exception exp) {
            System.debug('exp-->' + exp.getMessage());
            error = exp.getMessage();
        }
        Test.stopTest();
        System.assertEquals(error, 'Attempt to de-reference a null object');
    }

}